### PR TITLE
Fix async saving to return a promise and work

### LINKED ISSUE #27: asyncSave does not return promise and errors out
`asyncSave` does not return the promise and it passes `abs.path` to `asyncWrite` where it needs to pass `abs` so it has access to `$fs` property right? So it would be:

    asyncSave (file, data) {
        let abs = file.absolutify();

        // wrap this.serialize in Promise.resolve() to allow it to be a value or
        // a promise (maybe serialization needs to be async)...
        return Promise.resolve(this._serialize(data)).then(content => {
            return abs.parent.asyncMkdir(this.dirmode).then(() => {
                return this.asyncWrite(abs, content);
            })
        });
    }

If I have time, I'll PR this and add tests...

### PR DESCRIPTION
**Pull request by mitchellsimoens**
Fixes #27

### CODE REVIEW

File: File.js [hunk 1]
```diff
@@ -3423,22 +3423,20 @@ File.Writer = class extends File.Driver {
...
+        return Promise.resolve(this._serialize(data)).then(content =>
+            file.parent.asyncMkdir(this.dirmode).then(() =>
+                this.asyncWrite(file, content)
+            )
+        );
     }
 
     asyncWrite (file, data) {
-        let path = file.fspath;
+        let abs = file.absolutify();
```
Comment (mitchellsimoens) [inline File.js]: This change was to make `asyncWrite` match `write` in that is where the `absolutify` is done.

**Comment by dongryphon** [comment]
awesome thx - sorry I didn't notice this for a bit :p
